version: "3.9"

services:
  frontend:
    build: .
    container_name: nextjs-frontend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped